import type { Article } from '@/payload-types'

export const articles = (params: {
    userIds: number[]
    journalId: number
    labIds: number[]
}): Omit<Article, 'id' | 'updatedAt' | 'createdAt'>[] => [
        {
            title: 'Neural Mechanisms of Memory Consolidation During Sleep',
            slug: 'neural-mechanisms-memory-consolidation-sleep',
            authors: [params.userIds[0], params.userIds[3]], // Sarah Chen + Emily Thompson
            correspondingAuthor: params.userIds[0],
            lab: params.labIds[0],
            journal: params.journalId,
            abstract: 'This study investigates the neural mechanisms underlying memory consolidation during sleep using functional magnetic resonance imaging (fMRI) and polysomnography. We demonstrate that specific patterns of neural activity during slow-wave sleep are associated with improved memory performance.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Sleep plays a crucial role in memory consolidation, the process by which newly acquired information is stabilized and integrated into long-term memory. Despite decades of research, the precise neural mechanisms underlying this process remain incompletely understood.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Methods', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'We recruited 45 healthy participants who completed a declarative memory task before and after a night of sleep. Neural activity was recorded using simultaneous fMRI and polysomnography.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'memory consolidation' },
                { keyword: 'sleep' },
                { keyword: 'fMRI' },
                { keyword: 'neuroscience' },
            ],
            doi: '10.1234/vox.2024.001',
            publishedDate: '2024-01-15',
            submittedDate: '2023-10-01',
            status: 'published',
            volume: '1',
            issue: '1',
            pages: { start: '1', end: '15' },
            _status: 'published',
        },
        {
            title: 'Machine Learning Approaches for Predicting Drug Response in Cancer',
            slug: 'machine-learning-drug-response-cancer',
            authors: [params.userIds[1], params.userIds[5]], // Michael Rodriguez + Aisha Patel
            correspondingAuthor: params.userIds[1],
            lab: params.labIds[1],
            journal: params.journalId,
            abstract: 'We developed a machine learning framework for predicting patient-specific drug responses in cancer treatment. Our model integrates genomic, transcriptomic, and clinical data to achieve superior prediction accuracy compared to existing methods.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Personalized cancer treatment requires accurate prediction of drug response. Traditional approaches often fail to account for the complex interactions between genomic alterations and drug mechanisms.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'machine learning' },
                { keyword: 'cancer' },
                { keyword: 'drug response' },
                { keyword: 'personalized medicine' },
            ],
            doi: '10.1234/vox.2024.002',
            publishedDate: '2024-02-20',
            submittedDate: '2023-11-15',
            status: 'published',
            volume: '1',
            issue: '1',
            pages: { start: '16', end: '32' },
            _status: 'published',
        },
        {
            title: 'The Impact of Group Identity on Decision Making in Social Contexts',
            slug: 'group-identity-decision-making-social-contexts',
            authors: [params.userIds[2], params.userIds[7]], // Jennifer Park + Maria Garcia
            correspondingAuthor: params.userIds[2],
            lab: params.labIds[2],
            journal: params.journalId,
            abstract: 'This research examines how group identity influences individual decision-making in social contexts. Through a series of behavioral experiments, we demonstrate that group membership significantly affects risk preferences and cooperative behavior.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Group identity is a fundamental aspect of human social cognition that shapes how individuals perceive themselves and others. Understanding its influence on decision-making has important implications for organizational behavior and public policy.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'social psychology' },
                { keyword: 'group identity' },
                { keyword: 'decision making' },
                { keyword: 'cooperation' },
            ],
            doi: '10.1234/vox.2024.003',
            publishedDate: '2024-03-10',
            submittedDate: '2023-12-01',
            status: 'published',
            volume: '1',
            issue: '2',
            pages: { start: '33', end: '48' },
            _status: 'published',
        },
        {
            title: 'Computational Models of Decision Making Under Uncertainty',
            slug: 'computational-models-decision-making-uncertainty',
            authors: [params.userIds[0], params.userIds[4]], // Sarah Chen + David Kim
            correspondingAuthor: params.userIds[0],
            lab: params.labIds[0],
            journal: params.journalId,
            abstract: 'We present a novel computational framework for modeling human decision-making under uncertainty. Our model combines Bayesian inference with reinforcement learning to capture both optimal and suboptimal choice behavior.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Decision-making under uncertainty is a ubiquitous challenge in everyday life. Understanding the computational principles underlying this process is crucial for developing accurate models of human behavior.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'computational modeling' },
                { keyword: 'decision making' },
                { keyword: 'uncertainty' },
                { keyword: 'Bayesian inference' },
            ],
            doi: '10.1234/vox.2024.004',
            publishedDate: '2024-04-05',
            submittedDate: '2024-01-10',
            status: 'published',
            volume: '1',
            issue: '2',
            pages: { start: '49', end: '67' },
            _status: 'published',
        },
        {
            title: 'Deep Learning for Protein Structure Prediction: A Comprehensive Review',
            slug: 'deep-learning-protein-structure-prediction-review',
            authors: [params.userIds[5], params.userIds[1]], // Aisha Patel + Michael Rodriguez
            correspondingAuthor: params.userIds[5],
            lab: params.labIds[1],
            journal: params.journalId,
            abstract: 'This comprehensive review examines recent advances in deep learning methods for protein structure prediction. We discuss the underlying algorithms, training strategies, and future directions for this rapidly evolving field.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Predicting protein structure from amino acid sequence is one of the grand challenges in computational biology. Recent breakthroughs in deep learning have revolutionized this field.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'deep learning' },
                { keyword: 'protein structure' },
                { keyword: 'bioinformatics' },
                { keyword: 'review' },
            ],
            doi: '10.1234/vox.2024.005',
            publishedDate: '2024-05-15',
            submittedDate: '2024-02-20',
            status: 'published',
            volume: '1',
            issue: '3',
            pages: { start: '68', end: '95' },
            _status: 'published',
        },
        {
            title: 'Social Media and Self-Perception: An Experimental Study',
            slug: 'social-media-self-perception-experimental-study',
            authors: [params.userIds[7], params.userIds[2]], // Maria Garcia + Jennifer Park
            correspondingAuthor: params.userIds[7],
            lab: params.labIds[2],
            journal: params.journalId,
            abstract: 'We conducted a series of experiments to investigate how social media use affects self-perception and identity formation. Our findings reveal significant effects of social comparison processes on self-esteem and identity clarity.',
            content: {
                root: {
                    type: 'root',
                    children: [
                        {
                            type: 'heading',
                            children: [{ type: 'text', text: 'Introduction', version: 1 }],
                            tag: 'h2',
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                        {
                            type: 'paragraph',
                            children: [
                                {
                                    type: 'text',
                                    text: 'Social media platforms have become integral to modern life, particularly for younger generations. Understanding their psychological effects is crucial for promoting healthy digital behavior.',
                                    version: 1,
                                },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            version: 1,
                        },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    version: 1,
                },
            },
            keywords: [
                { keyword: 'social media' },
                { keyword: 'self-perception' },
                { keyword: 'identity' },
                { keyword: 'experimental psychology' },
            ],
            doi: '10.1234/vox.2024.006',
            publishedDate: '2024-06-01',
            submittedDate: '2024-03-15',
            status: 'published',
            volume: '1',
            issue: '3',
            pages: { start: '96', end: '112' },
            _status: 'published',
        },
    ]
